stages:
  - name: Build
    steps:
      - runScriptConfig:
          image: golang:1.11
          shellScript: |-
            mkdir -p /go/src/github.com/xiliangMa
            ln -s `pwd` /go/src/github.com/xiliangMa/restapi
            cd /go/src/github.com/xiliangMa/restapi
            go build -o bin/restapi
    artifacts:
      paths:
        - bin
        - conf
        - swagger

  - name: Publish
    steps:
      - publishImageConfig:
          dockerfilePath: ./Dockerfile
          buildContext: .
          tag: restapi:${CICD_EXECUTION_SEQUENCE}

  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./deployment.yaml