apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
      - name: restapi
        image: xiliangma/restapi:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: dev
          hostPort: 18080
          containerPort: 8080
        - name: prod
          hostPort: 18088
          containerPort: 8088
        - name: https
          hostPort: 1443
          containerPort: 443
        resources:
          limits:
            cpu: 1
            memory: 1024Mi
        livenessProbe:
          httpGet:
            path: /swagger
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3


