apiVersion: v1
kind: Service
metadata:
  name: restpi-service
spec:
  selector:
    app: restapi
  ports:
  - name: dev
    port: 18080
    targetPort: 18080
  - name: prod
    port: 18088
    targetPort: 18088
  - name: https
    port: 1443
    targetPort: 1443